"""update medical records

Revision ID: 01e38b45bc5e
Revises: cceae2f80c44
Create Date: 2026-02-10 18:55:26.233205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e38b45bc5e'
down_revision = 'cceae2f80c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_id', sa.Integer(), nullable=False))
        batch_op.drop_column('schedule_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('appointment_id')

    # ### end Alembic commands ###
