"""add attachment in patient background table

Revision ID: 04c63beb80bb
Revises: 5915a22f8102
Create Date: 2026-02-25 11:18:15.207152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c63beb80bb'
down_revision = '5915a22f8102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_history_background', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_history_background', schema=None) as batch_op:
        batch_op.drop_column('attachments')

    # ### end Alembic commands ###
