"""encrypt sensitive column

Revision ID: 1eb32739e236
Revises: c9a97c3e142f
Create Date: 2026-02-16 16:49:36.752867

"""
from alembic import op
import sqlalchemy as sa
from app.security.encrypted_column import EncryptedColumn


# revision identifiers, used by Alembic.
revision = '1eb32739e236'
down_revision = 'c9a97c3e142f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_record', schema=None) as batch_op:
        batch_op.alter_column('diagnosis',
               existing_type=sa.VARCHAR(),
               type_=EncryptedColumn(),
               existing_nullable=False)
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(),
               type_=EncryptedColumn(),
               existing_nullable=False)
        batch_op.alter_column('second_op',
               existing_type=sa.VARCHAR(),
               type_=EncryptedColumn(),
               existing_nullable=True)
        batch_op.alter_column('third_op',
               existing_type=sa.VARCHAR(),
               type_=EncryptedColumn(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_record', schema=None) as batch_op:
        batch_op.alter_column('third_op',
               existing_type=EncryptedColumn(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('second_op',
               existing_type=EncryptedColumn(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('notes',
               existing_type=EncryptedColumn(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('diagnosis',
               existing_type=EncryptedColumn(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
