"""added phone and email otp verification

Revision ID: 1fd60c1627be
Revises: 1c7851a42d90
Create Date: 2026-02-12 11:39:36.667618

"""
from alembic import op
import sqlalchemy as sa

from app.security.encrypted_column import EncryptedColumn


# revision identifiers, used by Alembic.
revision = '1fd60c1627be'
down_revision = '1c7851a42d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_otp', EncryptedColumn(), nullable=True))
        batch_op.add_column(sa.Column('phone_otp_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_otp', EncryptedColumn(), nullable=True))
        batch_op.add_column(sa.Column('email_otp_expiry', sa.DateTime(), nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('email_otp_expiry')
        batch_op.drop_column('email_otp')
        batch_op.drop_column('phone_otp_expiry')
        batch_op.drop_column('phone_otp')

    # ### end Alembic commands ###
