"""update medical visibility

Revision ID: 23a31de25ee3
Revises: 3065346aadc8
Create Date: 2026-02-11 15:02:06.940688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a31de25ee3'
down_revision = '3065346aadc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_record', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_medical_record_appointment_id", 'appointment', ['appointment_id'], ['appointment_id'])

    with op.batch_alter_table('medical_visibility', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pastMedicalHistory', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('beenHospitalized', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hadSurgery', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ongoingMedications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('familyHistory', sa.Boolean(), nullable=True))
        batch_op.drop_column('encrypted_state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_visibility', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_state', sa.TEXT(), nullable=False))
        batch_op.drop_column('familyHistory')
        batch_op.drop_column('ongoingMedications')
        batch_op.drop_column('allergies')
        batch_op.drop_column('hadSurgery')
        batch_op.drop_column('beenHospitalized')
        batch_op.drop_column('pastMedicalHistory')

    with op.batch_alter_table('medical_record', schema=None) as batch_op:
        batch_op.drop_constraint("fk_medical_record_appointment_id", type_='foreignkey')

    # ### end Alembic commands ###
