"""update reminder collumn in appointment

Revision ID: 45609d78a76e
Revises: 7675a57f4a6d
Create Date: 2026-02-17 12:31:48.855157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45609d78a76e'
down_revision = '7675a57f4a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_1hr_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reminder_ontime_sent', sa.Boolean(), nullable=True))
        batch_op.drop_column('reminder_sent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_sent', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
        batch_op.drop_column('reminder_ontime_sent')
        batch_op.drop_column('reminder_1hr_sent')

    # ### end Alembic commands ###
