"""initial schema

Revision ID: 541fe64a9808
Revises: 
Create Date: 2026-01-29 15:33:56.638771

"""
from alembic import op
import sqlalchemy as sa
from app.security.encrypted_column import EncryptedColumn


# revision identifiers, used by Alembic.
revision = '541fe64a9808'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('medical_visibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_state', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('doctor',
    sa.Column('doctor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('firstname', EncryptedColumn(), nullable=False),
    sa.Column('middlename', EncryptedColumn(), nullable=True),
    sa.Column('lastname', EncryptedColumn(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('bloodtype', EncryptedColumn(), nullable=True),
    sa.Column('height', EncryptedColumn(), nullable=True),
    sa.Column('weight', EncryptedColumn(), nullable=True),
    sa.Column('specialization', EncryptedColumn(), nullable=True),
    sa.Column('gender', EncryptedColumn(), nullable=False),
    sa.Column('dob', EncryptedColumn(), nullable=False),
    sa.Column('pob', EncryptedColumn(), nullable=False),
    sa.Column('civilstatus', EncryptedColumn(), nullable=False),
    sa.Column('degree', EncryptedColumn(), nullable=False),
    sa.Column('nationality', EncryptedColumn(), nullable=False),
    sa.Column('religion', EncryptedColumn(), nullable=False),
    sa.Column('phone', EncryptedColumn(), nullable=False),
    sa.Column('email', EncryptedColumn(), nullable=False),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('doctor_id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('patient',
    sa.Column('patient_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('firstname', EncryptedColumn(), nullable=False),
    sa.Column('middlename', EncryptedColumn(), nullable=True),
    sa.Column('lastname', EncryptedColumn(), nullable=False),
    sa.Column('gender', EncryptedColumn(), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('blood_type', EncryptedColumn(), nullable=True),
    sa.Column('civil_status', EncryptedColumn(), nullable=True),
    sa.Column('current_house_no', EncryptedColumn(), nullable=True),
    sa.Column('current_street', EncryptedColumn(), nullable=True),
    sa.Column('current_barangay', EncryptedColumn(), nullable=True),
    sa.Column('current_city', EncryptedColumn(), nullable=True),
    sa.Column('current_province', EncryptedColumn(), nullable=True),
    sa.Column('current_zipcode', EncryptedColumn(), nullable=True),
    sa.Column('permanent_house_no', EncryptedColumn(), nullable=False),
    sa.Column('permanent_street', EncryptedColumn(), nullable=True),
    sa.Column('permanent_barangay', EncryptedColumn(), nullable=False),
    sa.Column('permanent_city', EncryptedColumn(), nullable=False),
    sa.Column('permanent_province', EncryptedColumn(), nullable=False),
    sa.Column('permanent_zipcode', EncryptedColumn(), nullable=False),
    sa.Column('phone', EncryptedColumn(), nullable=False),
    sa.Column('email', EncryptedColumn(), nullable=True),
    sa.Column('ec_name', EncryptedColumn(), nullable=True),
    sa.Column('ec_phone', EncryptedColumn(), nullable=True),
    sa.Column('ec_relation', EncryptedColumn(), nullable=True),
    sa.Column('ec_address', EncryptedColumn(), nullable=True),
    sa.Column('profile_image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('appointment',
    sa.Column('appointment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.String(length=10), nullable=False),
    sa.Column('appointment_time', sa.String(length=10), nullable=False),
    sa.Column('reason', EncryptedColumn(), nullable=True),
    sa.Column('notes', EncryptedColumn(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('doctor_schedule',
    sa.Column('doctor_schedule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('vacant_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ),
    sa.PrimaryKeyConstraint('doctor_schedule_id'),
    sa.UniqueConstraint('doctor_id', 'vacant_date', 'start_time', 'end_time', name='uq_doctor_slot')
    )
    op.create_table('patient_history_background',
    sa.Column('phb_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('pastMedicalHistory', EncryptedColumn(), nullable=True),
    sa.Column('beenHospitalized', EncryptedColumn(), nullable=True),
    sa.Column('hadSurgery', EncryptedColumn(), nullable=True),
    sa.Column('allergies', EncryptedColumn(), nullable=True),
    sa.Column('ongoingMedications', EncryptedColumn(), nullable=True),
    sa.Column('familyHistory', EncryptedColumn(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('phb_id')
    )
    op.create_table('medical_record',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.String(length=10), nullable=False),
    sa.Column('diagnosis', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['doctor_schedule.doctor_schedule_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('payment_record',
    sa.Column('payment_record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.String(length=20), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointment_id'], ),
    sa.PrimaryKeyConstraint('payment_record_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_record')
    op.drop_table('medical_record')
    op.drop_table('patient_history_background')
    op.drop_table('doctor_schedule')
    op.drop_table('appointment')
    op.drop_table('patient')
    op.drop_table('doctor')
    op.drop_table('user')
    op.drop_table('medical_visibility')
    op.drop_table('account')
    # ### end Alembic commands ###
