"""fix medical_visibility relationship

Revision ID: 649c5afa0f1a
Revises: d4064c05ec05
Create Date: 2026-02-11 15:17:46.088102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649c5afa0f1a'
down_revision = 'd4064c05ec05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_visibility', schema=None) as batch_op:
        batch_op.alter_column('pastMedicalHistory',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('beenHospitalized',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('hadSurgery',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('allergies',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('ongoingMedications',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('familyHistory',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('socialHistory',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('immunizations',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('recentTravelHistory',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('otherRelevantInfo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_foreign_key("fk_medical_visibility_patient_id", 'patient', ['patient_id'], ['patient_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_visibility', schema=None) as batch_op:
        batch_op.drop_constraint("fk_medical_visibility_patient_id", type_='foreignkey')
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('otherRelevantInfo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('recentTravelHistory',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('immunizations',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('socialHistory',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('familyHistory',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('ongoingMedications',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('allergies',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('hadSurgery',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('beenHospitalized',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('pastMedicalHistory',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
