"""Refactor patient address to structured fields

Revision ID: 6b0f90a58b37
Revises: 
Create Date: 2026-01-20 10:19:57.009306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0f90a58b37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_house_no', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('current_street', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('current_barangay', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('current_city', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('current_province', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('current_zipcode', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('permanent_house_no', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('permanent_street', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('permanent_barangay', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('permanent_city', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('permanent_province', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('permanent_zipcode', sa.String(length=10), nullable=False))
        batch_op.drop_column('current_address')
        batch_op.drop_column('permanent_address')
        batch_op.drop_column('zipcode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zipcode', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('permanent_address', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('current_address', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('permanent_zipcode')
        batch_op.drop_column('permanent_province')
        batch_op.drop_column('permanent_city')
        batch_op.drop_column('permanent_barangay')
        batch_op.drop_column('permanent_street')
        batch_op.drop_column('permanent_house_no')
        batch_op.drop_column('current_zipcode')
        batch_op.drop_column('current_province')
        batch_op.drop_column('current_city')
        batch_op.drop_column('current_barangay')
        batch_op.drop_column('current_street')
        batch_op.drop_column('current_house_no')

    # ### end Alembic commands ###
