"""added table appointment visibility

Revision ID: 714bbf08ca75
Revises: 1eb32739e236
Create Date: 2026-02-16 19:14:57.144238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714bbf08ca75'
down_revision = '1eb32739e236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_visibility',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('visibility_meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment_visibility')
    # ### end Alembic commands ###
