"""Changed amount to float

Revision ID: 715dd0aaaccd
Revises: 1fd60c1627be
Create Date: 2026-02-16 14:11:59.565537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715dd0aaaccd'
down_revision = '1fd60c1627be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_record', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_record', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
