"""reminder collumn in appointment

Revision ID: 7675a57f4a6d
Revises: 714bbf08ca75
Create Date: 2026-02-17 12:25:21.608091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7675a57f4a6d'
down_revision = '714bbf08ca75'
branch_labels = None
depends_on = None

def upgrade():
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'reminder_sent',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('0')  # SQLite boolean false
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('reminder_sent')

    # ### end Alembic commands ###
