"""add doctor status active/inactive

Revision ID: 8d7ee134703a
Revises: 04c63beb80bb
Create Date: 2026-02-25 18:04:13.015518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7ee134703a'
down_revision = '04c63beb80bb'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'status',
                sa.String(length=50),
                nullable=False,
                server_default='active'   # ✅ THIS FIXES IT
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
