"""create doctors_background model

Revision ID: 943f04fdbcc4
Revises: 797f80a47e83
Create Date: 2026-02-04 10:33:16.138101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943f04fdbcc4'
down_revision = '797f80a47e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors_background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('organization', sa.String(length=150), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('clinic_name', sa.String(length=150), nullable=True),
    sa.Column('clinic_address', sa.String(length=255), nullable=True),
    sa.Column('clinic_days', sa.String(length=100), nullable=True),
    sa.Column('clinic_hours_from', sa.String(length=100), nullable=True),
    sa.Column('clinic_hours_to', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctors_background')
    # ### end Alembic commands ###
