"""Fix EncryptedColumn instantiation for Patient and Doctor

Revision ID: aac5b7c815b4
Revises: 0d18af7b45dc
Create Date: 2026-01-22 14:01:23.242297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac5b7c815b4'
down_revision = '0d18af7b45dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(length=50),
               type_=app.security.encrypted_column.EncryptedColumn(),
               existing_nullable=False)
        batch_op.alter_column('middlename',
               existing_type=sa.VARCHAR(length=50),
               type_=app.security.encrypted_column.EncryptedColumn(),
               existing_nullable=True)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=50),
               type_=app.security.encrypted_column.EncryptedColumn(),
               existing_nullable=False)
        batch_op.alter_column('bloodtype',
               existing_type=sa.VARCHAR(length=5),
               type_=app.security.encrypted_column.EncryptedColumn(),
               existing_nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(),
               type_=app.security.encrypted_column.EncryptedColumn(),
               existing_nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.VARCHAR(),
               type_=app.security.encrypted_column.EncryptedColumn(),
               existing_nullable=True)
        batch_op.alter_column('specialization',
               existing_type=sa.VARCHAR(length=100),
               type_=app.security.encrypted_column.EncryptedColumn(),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=20),
               type_=app.security.encrypted_column.EncryptedColumn(),
               existing_nullable=False)
        batch_op.alter_column('dob',
               existing_type=sa.VARCHAR(length=10),
               type_=app.security.encrypted_column.EncryptedColumn(),
               existing_nullable=False)
        batch_op.alter_column('pob',
               existing_type=sa.VARCHAR(length=100),
               type_=app.security.encrypted_column.EncryptedColumn(),
               nullable=False)
        batch_op.alter_column('civilstatus',
               existing_type=sa.VARCHAR(length=20),
               type_=app.security.encrypted_column.EncryptedColumn(),
               nullable=False)
        batch_op.alter_column('degree',
               existing_type=sa.VARCHAR(length=100),
               type_=app.security.encrypted_column.EncryptedColumn(),
               nullable=False)
        batch_op.alter_column('nationality',
               existing_type=sa.VARCHAR(length=50),
               type_=app.security.encrypted_column.EncryptedColumn(),
               nullable=False)
        batch_op.alter_column('religion',
               existing_type=sa.VARCHAR(length=50),
               type_=app.security.encrypted_column.EncryptedColumn(),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               type_=app.security.encrypted_column.EncryptedColumn(),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=app.security.encrypted_column.EncryptedColumn(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=app.security.encrypted_column.EncryptedColumn(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=app.security.encrypted_column.EncryptedColumn(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('religion',
               existing_type=app.security.encrypted_column.EncryptedColumn(),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('nationality',
               existing_type=app.security.encrypted_column.EncryptedColumn(),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('degree',
               existing_type=app.security.encrypted_column.EncryptedColumn(),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('civilstatus',
               existing_type=app.security.encrypted_column.EncryptedColumn(),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('pob',
               existing_type=app.security.encrypted_column.EncryptedColumn(),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('dob',
               existing_type=app.security.encrypted_column.EncryptedColumn(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('gender',
               existing_type=app.security.encrypted_column.EncryptedColumn(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('specialization',
               existing_type=app.security.encrypted_column.EncryptedColumn(),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('weight',
               existing_type=app.security.encrypted_column.EncryptedColumn(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('height',
               existing_type=app.security.encrypted_column.EncryptedColumn(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('bloodtype',
               existing_type=app.security.encrypted_column.EncryptedColumn(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
        batch_op.alter_column('lastname',
               existing_type=app.security.encrypted_column.EncryptedColumn(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('middlename',
               existing_type=app.security.encrypted_column.EncryptedColumn(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('firstname',
               existing_type=app.security.encrypted_column.EncryptedColumn(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
