"""updated medical Record added collumn for 2nd and 3rd opinion

Revision ID: c9a97c3e142f
Revises: a4d0ee9f46c3
Create Date: 2026-02-16 15:49:30.071711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a97c3e142f'
down_revision = 'a4d0ee9f46c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_op', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('third_op', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_record', schema=None) as batch_op:
        batch_op.drop_column('third_op')
        batch_op.drop_column('second_op')

    # ### end Alembic commands ###
