"""add type in appointment

Revision ID: cceae2f80c44
Revises: 943f04fdbcc4
Create Date: 2026-02-09 14:49:09.685105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cceae2f80c44'
down_revision = '943f04fdbcc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('type', sa.String(length=30), nullable=False, server_default='General')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
