"""update medical visibility 1.1

Revision ID: d4064c05ec05
Revises: 23a31de25ee3
Create Date: 2026-02-11 15:10:56.787287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4064c05ec05'
down_revision = '23a31de25ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_visibility', schema=None) as batch_op:
        batch_op.add_column(sa.Column('socialHistory', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('immunizations', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recentTravelHistory', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('otherRelevantInfo', sa.Boolean(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_visibility', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('otherRelevantInfo')
        batch_op.drop_column('recentTravelHistory')
        batch_op.drop_column('immunizations')
        batch_op.drop_column('socialHistory')

    # ### end Alembic commands ###
