"""update account model add last login for account disabling

Revision ID: e9872d2beb8e
Revises: 8d7ee134703a
Create Date: 2026-02-26 14:11:28.699084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9872d2beb8e'
down_revision = '8d7ee134703a'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'last_login_at',
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now()   # ← fills existing rows with current timestamp
        ))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')

    # ### end Alembic commands ###
